default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: <%= ENV['USERNAME'] %>
      password: <%= ENV['PASSWORD'] %>
      host:     <%= ENV['IP'] %>



development:
  <<: *default
  template: template0
  database: sample_app_development

test:
  <<: *default
  template: template0
  database: sample_app_test

production:
  <<: *default
  template: template0
  database: sample_app_production